In [2]:
import pandas as pd
import numpy as np
import random
import string
from flask_bcrypt import Bcrypt
bcrypt = Bcrypt()
import json

## Cleaning dataset degli utenti

In [ ]:
df_utenti = pd.read_csv("datasets/users_cleaned.csv")

In [10]:

df_utenti = df_utenti.drop(columns=["user_watching", "user_completed","user_onhold","user_dropped","user_plantowatch","user_days_spent_watching", "access_rank", "stats_mean_score", "stats_rewatched", "stats_episodes","user_days_spent_watching"])
df_utenti = df_utenti.reset_index(drop=True)

In [11]:
df_utenti

,username,user_id,gender,location,birth_date,join_date,last_online
0,karthiga,2255153,Female,"Chennai, India",1990-04-29 00:00:00,2013-03-03 00:00:00,2014-02-04 01:32:00
1,Damonashu,37326,Male,"Detroit,Michigan",1991-08-01 00:00:00,2008-02-13 00:00:00,2017-07-10 06:52:54
2,bskai,228342,Male,"Nayarit, Mexico",1990-12-14 00:00:00,2009-08-31 00:00:00,2014-05-12 16:35:00
3,terune_uzumaki,327311,Female,"Malaysia, Kuantan",1998-08-24 00:00:00,2010-05-10 00:00:00,2012-10-18 19:06:00
4,Bas_G,5015094,Male,"Nijmegen, Nederland",1999-10-24 00:00:00,2015-11-26 00:00:00,2018-05-10 20:53:37
...,...,...,...,...,...,...,...
108706,isoann,797785,Male,Poland:,1997-01-13 00:00:00,2011-10-23 00:00:00,2018-02-25 01:20:27
108707,bumcakee,1396285,Female,"nhollywood, california",1998-07-18 00:00:00,2012-07-14 00:00:00,2017-02-14 00:30:00
108708,Scarlet95,2478991,Female,Belgium,1995-10-17 00:00:00,2013-04-24 00:00:00,2016-12-18 08:41:00
108709,Torasori,3975907,Male,"Latvia, Riga",1998-11-18 00:00:00,2014-07-30 00:00:00,2018-05-24 21:34:46
108710,HMicca,1289601,Female,"Birmingham, England",1995-08-12 00:00:00,2012-05-05 00:00:00,2012-11-15 08:10:00

In [12]:
def genera_password(lunghezza=10):
    caratteri = string.ascii_letters + string.digits
    return ''.join(random.choices(caratteri, k=lunghezza))

df_utenti['password'] = [genera_password() for _ in range(len(df_utenti))]

In [14]:
# Salvataggio username e password in chiaro in un file .txt
with open("datasets/credenziali.txt", "w") as f:
    for _, row in df_utenti.iterrows():
        f.write(f"{row['username']}:{row['password']}\n")

print("Credenziali salvate in datasets/credenziali.txt")

# Criptazione delle password con controllo visivo
for i, pw in enumerate(df_utenti['password']):
    hashed = bcrypt.generate_password_hash(pw).decode('utf-8')
    df_utenti.at[i, 'password'] = hashed
    if i % 100 == 0:
        print(f"{i} password criptate...")

print("Criptazione completata.")

Credenziali salvate in datasets/credenziali.txt
0 password criptate...
100 password criptate...
200 password criptate...
300 password criptate...
400 password criptate...
500 password criptate...
600 password criptate...
700 password criptate...
800 password criptate...
900 password criptate...
1000 password criptate...
1100 password criptate...
1200 password criptate...
1300 password criptate...
1400 password criptate...
1500 password criptate...
1600 password criptate...
1700 password criptate...
1800 password criptate...
1900 password criptate...
2000 password criptate...
2100 password criptate...
2200 password criptate...
2300 password criptate...
2400 password criptate...
2500 password criptate...
2600 password criptate...
2700 password criptate...
2800 password criptate...
2900 password criptate...
3000 password criptate...
3100 password criptate...
3200 password criptate...
3300 password criptate...
3400 password criptate...
3500 password criptate...
3600 password criptate...
3700 password criptate...
3800 password criptate...
3900 password criptate...
4000 password criptate...
4100 password criptate...
4200 password criptate...
4300 password criptate...
4400 password criptate...
4500 password criptate...
4600 password criptate...
4700 password criptate...
4800 password criptate...
4900 password criptate...
5000 password criptate...
5100 password criptate...
5200 password criptate...
5300 password criptate...
5400 password criptate...
5500 password criptate...
5600 password criptate...
5700 password criptate...
5800 password criptate...
5900 password criptate...
6000 password criptate...
6100 password criptate...
6200 password criptate...
6300 password criptate...
6400 password criptate...
6500 password criptate...
6600 password criptate...
6700 password criptate...
6800 password criptate...
6900 password criptate...
7000 password criptate...
7100 password criptate...
7200 password criptate...
7300 password criptate...
7400 password criptate...
7500 password criptate...
7600 password criptate...
7700 password criptate...
7800 password criptate...
7900 password criptate...
8000 password criptate...
8100 password criptate...
8200 password criptate...
8300 password criptate...
8400 password criptate...
8500 password criptate...
8600 password criptate...
8700 password criptate...
8800 password criptate...
8900 password criptate...
9000 password criptate...
9100 password criptate...
9200 password criptate...
9300 password criptate...
9400 password criptate...
9500 password criptate...
9600 password criptate...
9700 password criptate...
9800 password criptate...
9900 password criptate...
10000 password criptate...
10100 password criptate...
10200 password criptate...
10300 password criptate...
10400 password criptate...
10500 password criptate...
10600 password criptate...
10700 password criptate...
10800 password criptate...
10900 password criptate...
11000 password criptate...
11100 password criptate...
11200 password criptate...
11300 password criptate...
11400 password criptate...
11500 password criptate...
11600 password criptate...
11700 password criptate...
11800 password criptate...
11900 password criptate...
12000 password criptate...
12100 password criptate...
12200 password criptate...
12300 password criptate...
12400 password criptate...
12500 password criptate...
12600 password criptate...
12700 password criptate...
12800 password criptate...
12900 password criptate...
13000 password criptate...
13100 password criptate...
13200 password criptate...
13300 password criptate...
13400 password criptate...
13500 password criptate...
13600 password criptate...
13700 password criptate...
13800 password criptate...
13900 password criptate...
14000 password criptate...
14100 password criptate...
14200 password criptate...
14300 password criptate...
14400 password criptate...
14500 password criptate...
14600 password criptate...
14700 password criptate...
14800 password criptate...
14900 password criptate...
15000 password criptate...
15100 password criptate...
15200 password criptate...
15300 password criptate...
15400 password criptate...
15500 password criptate...
15600 password criptate...
15700 password criptate...
15800 password criptate...
15900 password criptate...
16000 password criptate...
16100 password criptate...
16200 password criptate...
16300 password criptate...
16400 password criptate...
16500 password criptate...
16600 password criptate...
16700 password criptate...
16800 password criptate...
16900 password criptate...
17000 password criptate...
17100 password criptate...
17200 password criptate...
17300 password criptate...
17400 password criptate...
17500 password criptate...
17600 password criptate...
17700 password criptate...
17800 password criptate...
17900 password criptate...
18000 password criptate...
18100 password criptate...
18200 password criptate...
18300 password criptate...
18400 password criptate...
18500 password criptate...
18600 password criptate...
18700 password criptate...
18800 password criptate...
18900 password criptate...
19000 password criptate...
19100 password criptate...
19200 password criptate...
19300 password criptate...
19400 password criptate...
19500 password criptate...
19600 password criptate...
19700 password criptate...
19800 password criptate...
19900 password criptate...
20000 password criptate...
20100 password criptate...
20200 password criptate...
20300 password criptate...
20400 password criptate...
20500 password criptate...
20600 password criptate...
20700 password criptate...
20800 password criptate...
20900 password criptate...
21000 password criptate...
21100 password criptate...
21200 password criptate...
21300 password criptate...
21400 password criptate...
21500 password criptate...
21600 password criptate...
21700 password criptate...
21800 password criptate...
21900 password criptate...
22000 password criptate...
22100 password criptate...
22200 password criptate...
22300 password criptate...
22400 password criptate...
22500 password criptate...
22600 password criptate...
22700 password criptate...
22800 password criptate...
22900 password criptate...
23000 password criptate...
23100 password criptate...
23200 password criptate...
23300 password criptate...
23400 password criptate...
23500 password criptate...
23600 password criptate...
23700 password criptate...
23800 password criptate...
23900 password criptate...
24000 password criptate...
24100 password criptate...
24200 password criptate...
24300 password criptate...
24400 password criptate...
24500 password criptate...
24600 password criptate...
24700 password criptate...
24800 password criptate...
24900 password criptate...
25000 password criptate...
25100 password criptate...
25200 password criptate...
25300 password criptate...
25400 password criptate...
25500 password criptate...
25600 password criptate...
25700 password criptate...
25800 password criptate...
25900 password criptate...
26000 password criptate...
26100 password criptate...
26200 password criptate...
26300 password criptate...
26400 password criptate...
26500 password criptate...
26600 password criptate...
26700 password criptate...
26800 password criptate...
26900 password criptate...
27000 password criptate...
27100 password criptate...
27200 password criptate...
27300 password criptate...
27400 password criptate...
27500 password criptate...
27600 password criptate...
27700 password criptate...
27800 password criptate...
27900 password criptate...
28000 password criptate...
28100 password criptate...
28200 password criptate...
28300 password criptate...
28400 password criptate...
28500 password criptate...
28600 password criptate...
28700 password criptate...
28800 password criptate...
28900 password criptate...
29000 password criptate...
29100 password criptate...
29200 password criptate...
29300 password criptate...
29400 password criptate...
29500 password criptate...
29600 password criptate...
29700 password criptate...
29800 password criptate...
29900 password criptate...
30000 password criptate...
30100 password criptate...
30200 password criptate...
30300 password criptate...
30400 password criptate...
30500 password criptate...
30600 password criptate...
30700 password criptate...
30800 password criptate...
30900 password criptate...
31000 password criptate...
31100 password criptate...
31200 password criptate...
31300 password criptate...
31400 password criptate...
31500 password criptate...
31600 password criptate...
31700 password criptate...
31800 password criptate...
31900 password criptate...
32000 password criptate...
32100 password criptate...
32200 password criptate...
32300 password criptate...
32400 password criptate...
32500 password criptate...
32600 password criptate...
32700 password criptate...
32800 password criptate...
32900 password criptate...
33000 password criptate...
33100 password criptate...
33200 password criptate...
33300 password criptate...
33400 password criptate...
33500 password criptate...
33600 password criptate...
33700 password criptate...
33800 password criptate...
33900 password criptate...
34000 password criptate...
34100 password criptate...
34200 password criptate...
34300 password criptate...
34400 password criptate...
34500 password criptate...
34600 password criptate...
34700 password criptate...
34800 password criptate...
34900 password criptate...
35000 password criptate...
35100 password criptate...
35200 password criptate...
35300 password criptate...
35400 password criptate...
35500 password criptate...
35600 password criptate...
35700 password criptate...
35800 password criptate...
35900 password criptate...
36000 password criptate...
36100 password criptate...
36200 password criptate...
36300 password criptate...
36400 password criptate...
36500 password criptate...
36600 password criptate...
36700 password criptate...
36800 password criptate...
36900 password criptate...
37000 password criptate...
37100 password criptate...
37200 password criptate...
37300 password criptate...
37400 password criptate...
37500 password criptate...
37600 password criptate...
37700 password criptate...
37800 password criptate...
37900 password criptate...
38000 password criptate...
38100 password criptate...
38200 password criptate...
38300 password criptate...
38400 password criptate...
38500 password criptate...
38600 password criptate...
38700 password criptate...
38800 password criptate...
38900 password criptate...
39000 password criptate...
39100 password criptate...
39200 password criptate...
39300 password criptate...
39400 password criptate...
39500 password criptate...
39600 password criptate...
39700 password criptate...
39800 password criptate...
39900 password criptate...
40000 password criptate...
40100 password criptate...
40200 password criptate...
40300 password criptate...
40400 password criptate...
40500 password criptate...
40600 password criptate...
40700 password criptate...
40800 password criptate...
40900 password criptate...
41000 password criptate...
41100 password criptate...
41200 password criptate...
41300 password criptate...
41400 password criptate...
41500 password criptate...
41600 password criptate...
41700 password criptate...
41800 password criptate...
41900 password criptate...
42000 password criptate...
42100 password criptate...
42200 password criptate...
42300 password criptate...
42400 password criptate...
42500 password criptate...
42600 password criptate...
42700 password criptate...
42800 password criptate...
42900 password criptate...
43000 password criptate...
43100 password criptate...
43200 password criptate...
43300 password criptate...
43400 password criptate...
43500 password criptate...
43600 password criptate...
43700 password criptate...
43800 password criptate...
43900 password criptate...
44000 password criptate...
44100 password criptate...
44200 password criptate...
44300 password criptate...
44400 password criptate...
44500 password criptate...
44600 password criptate...
44700 password criptate...
44800 password criptate...
44900 password criptate...
45000 password criptate...
45100 password criptate...
45200 password criptate...
45300 password criptate...
45400 password criptate...
45500 password criptate...
45600 password criptate...
45700 password criptate...
45800 password criptate...
45900 password criptate...
46000 password criptate...
46100 password criptate...
46200 password criptate...
46300 password criptate...
46400 password criptate...
46500 password criptate...
46600 password criptate...
46700 password criptate...
46800 password criptate...
46900 password criptate...
47000 password criptate...
47100 password criptate...
47200 password criptate...
47300 password criptate...
47400 password criptate...
47500 password criptate...
47600 password criptate...
47700 password criptate...
47800 password criptate...
47900 password criptate...
48000 password criptate...
48100 password criptate...
48200 password criptate...
48300 password criptate...
48400 password criptate...
48500 password criptate...
48600 password criptate...
48700 password criptate...
48800 password criptate...
48900 password criptate...
49000 password criptate...
49100 password criptate...
49200 password criptate...
49300 password criptate...
49400 password criptate...
49500 password criptate...
49600 password criptate...
49700 password criptate...
49800 password criptate...
49900 password criptate...
50000 password criptate...
50100 password criptate...
50200 password criptate...
50300 password criptate...
50400 password criptate...
50500 password criptate...
50600 password criptate...
50700 password criptate...
50800 password criptate...
50900 password criptate...
51000 password criptate...
51100 password criptate...
51200 password criptate...
51300 password criptate...
51400 password criptate...
51500 password criptate...
51600 password criptate...
51700 password criptate...
51800 password criptate...
51900 password criptate...
52000 password criptate...
52100 password criptate...
52200 password criptate...
52300 password criptate...
52400 password criptate...
52500 password criptate...
52600 password criptate...
52700 password criptate...
52800 password criptate...
52900 password criptate...
53000 password criptate...
53100 password criptate...
53200 password criptate...
53300 password criptate...
53400 password criptate...
53500 password criptate...
53600 password criptate...
53700 password criptate...
53800 password criptate...
53900 password criptate...
54000 password criptate...
54100 password criptate...
54200 password criptate...
54300 password criptate...
54400 password criptate...
54500 password criptate...
54600 password criptate...
54700 password criptate...
54800 password criptate...
54900 password criptate...
55000 password criptate...
55100 password criptate...
55200 password criptate...
55300 password criptate...
55400 password criptate...
55500 password criptate...
55600 password criptate...
55700 password criptate...
55800 password criptate...
55900 password criptate...
56000 password criptate...
56100 password criptate...
56200 password criptate...
56300 password criptate...
56400 password criptate...
56500 password criptate...
56600 password criptate...
56700 password criptate...
56800 password criptate...
56900 password criptate...
57000 password criptate...
57100 password criptate...
57200 password criptate...
57300 password criptate...
57400 password criptate...
57500 password criptate...
57600 password criptate...
57700 password criptate...
57800 password criptate...
57900 password criptate...
58000 password criptate...
58100 password criptate...
58200 password criptate...
58300 password criptate...
58400 password criptate...
58500 password criptate...
58600 password criptate...
58700 password criptate...
58800 password criptate...
58900 password criptate...
59000 password criptate...
59100 password criptate...
59200 password criptate...
59300 password criptate...
59400 password criptate...
59500 password criptate...
59600 password criptate...
59700 password criptate...
59800 password criptate...
59900 password criptate...
60000 password criptate...
60100 password criptate...
60200 password criptate...
60300 password criptate...
60400 password criptate...
60500 password criptate...
60600 password criptate...
60700 password criptate...
60800 password criptate...
60900 password criptate...
61000 password criptate...
61100 password criptate...
61200 password criptate...
61300 password criptate...
61400 password criptate...
61500 password criptate...
61600 password criptate...
61700 password criptate...
61800 password criptate...
61900 password criptate...
62000 password criptate...
62100 password criptate...
62200 password criptate...
62300 password criptate...
62400 password criptate...
62500 password criptate...
62600 password criptate...
62700 password criptate...
62800 password criptate...
62900 password criptate...
63000 password criptate...
63100 password criptate...
63200 password criptate...
63300 password criptate...
63400 password criptate...
63500 password criptate...
63600 password criptate...
63700 password criptate...
63800 password criptate...
63900 password criptate...
64000 password criptate...
64100 password criptate...
64200 password criptate...
64300 password criptate...
64400 password criptate...
64500 password criptate...
64600 password criptate...
64700 password criptate...
64800 password criptate...
64900 password criptate...
65000 password criptate...
65100 password criptate...
65200 password criptate...
65300 password criptate...
65400 password criptate...
65500 password criptate...
65600 password criptate...
65700 password criptate...
65800 password criptate...
65900 password criptate...
66000 password criptate...
66100 password criptate...
66200 password criptate...
66300 password criptate...
66400 password criptate...
66500 password criptate...
66600 password criptate...
66700 password criptate...
66800 password criptate...
66900 password criptate...
67000 password criptate...
67100 password criptate...
67200 password criptate...
67300 password criptate...
67400 password criptate...
67500 password criptate...
67600 password criptate...
67700 password criptate...
67800 password criptate...
67900 password criptate...
68000 password criptate...
68100 password criptate...
68200 password criptate...
68300 password criptate...
68400 password criptate...
68500 password criptate...
68600 password criptate...
68700 password criptate...
68800 password criptate...
68900 password criptate...
69000 password criptate...
69100 password criptate...
69200 password criptate...
69300 password criptate...
69400 password criptate...
69500 password criptate...
69600 password criptate...
69700 password criptate...
69800 password criptate...
69900 password criptate...
70000 password criptate...
70100 password criptate...
70200 password criptate...
70300 password criptate...
70400 password criptate...
70500 password criptate...
70600 password criptate...
70700 password criptate...
70800 password criptate...
70900 password criptate...
71000 password criptate...
71100 password criptate...
71200 password criptate...
71300 password criptate...
71400 password criptate...
71500 password criptate...
71600 password criptate...
71700 password criptate...
71800 password criptate...
71900 password criptate...
72000 password criptate...
72100 password criptate...
72200 password criptate...
72300 password criptate...
72400 password criptate...
72500 password criptate...
72600 password criptate...
72700 password criptate...
72800 password criptate...
72900 password criptate...
73000 password criptate...
73100 password criptate...
73200 password criptate...
73300 password criptate...
73400 password criptate...
73500 password criptate...
73600 password criptate...
73700 password criptate...
73800 password criptate...
73900 password criptate...
74000 password criptate...
74100 password criptate...
74200 password criptate...

In [15]:
df_utenti

,username,user_id,gender,location,birth_date,join_date,last_online,password
0,karthiga,2255153,Female,"Chennai, India",1990-04-29 00:00:00,2013-03-03 00:00:00,2014-02-04 01:32:00,$2b$12$zXHZLS5lW3x1Dsj0.9x8POmrThwI053Ey2jb094...
1,Damonashu,37326,Male,"Detroit,Michigan",1991-08-01 00:00:00,2008-02-13 00:00:00,2017-07-10 06:52:54,$2b$12$ORndjTUFxZexvjUJEeONcOQHUUOkbw7dICUr7fs...
2,bskai,228342,Male,"Nayarit, Mexico",1990-12-14 00:00:00,2009-08-31 00:00:00,2014-05-12 16:35:00,$2b$12$Xm9lfi62V0McWvSTPvXvtOZ604DEVdJG7OTmowg...
3,terune_uzumaki,327311,Female,"Malaysia, Kuantan",1998-08-24 00:00:00,2010-05-10 00:00:00,2012-10-18 19:06:00,$2b$12$8sbo6xH9thvzVoPC97JDzuj2wPdGN7f8xg.fLtW...
4,Bas_G,5015094,Male,"Nijmegen, Nederland",1999-10-24 00:00:00,2015-11-26 00:00:00,2018-05-10 20:53:37,$2b$12$eN2shvFkaKiPlpuWcxv4DOVZWHVdUSQZXpAzDtX...
...,...,...,...,...,...,...,...,...
108706,isoann,797785,Male,Poland:,1997-01-13 00:00:00,2011-10-23 00:00:00,2018-02-25 01:20:27,$2b$12$PyESVZdVuWSqr.R6ieoolOX9RuriQgQgu6anI7r...
108707,bumcakee,1396285,Female,"nhollywood, california",1998-07-18 00:00:00,2012-07-14 00:00:00,2017-02-14 00:30:00,$2b$12$/pDgKKnkAFiHr3sM3hPlC.nLj1eQS2x1l4Ksdke...
108708,Scarlet95,2478991,Female,Belgium,1995-10-17 00:00:00,2013-04-24 00:00:00,2016-12-18 08:41:00,$2b$12$Rje5pFgEBt5RRz2EUQoon.eAVdte.X4rHP3BA4n...
108709,Torasori,3975907,Male,"Latvia, Riga",1998-11-18 00:00:00,2014-07-30 00:00:00,2018-05-24 21:34:46,$2b$12$m7Xkul283lL6WFCCcUeisuuGYUt8LBG04WF1XgA...
108710,HMicca,1289601,Female,"Birmingham, England",1995-08-12 00:00:00,2012-05-05 00:00:00,2012-11-15 08:10:00,$2b$12$3z9V0m/lhn08g./ogNSGJ.711ovXA.c0OkpGt35...

In [16]:
domini_email = [
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "hotmail.com",
    "icloud.com",
    "protonmail.com",
    "aol.com",
    "zoho.com",
    "mail.com",
    "gmx.com"
]

df_utenti['email'] = [
    f"{username}@{domini_email[i % len(domini_email)]}"
    for i, username in enumerate(df_utenti['username'])
]

In [17]:
df_utenti

,username,user_id,gender,location,birth_date,join_date,last_online,password,email
0,karthiga,2255153,Female,"Chennai, India",1990-04-29 00:00:00,2013-03-03 00:00:00,2014-02-04 01:32:00,$2b$12$zXHZLS5lW3x1Dsj0.9x8POmrThwI053Ey2jb094...,karthiga@gmail.com
1,Damonashu,37326,Male,"Detroit,Michigan",1991-08-01 00:00:00,2008-02-13 00:00:00,2017-07-10 06:52:54,$2b$12$ORndjTUFxZexvjUJEeONcOQHUUOkbw7dICUr7fs...,Damonashu@yahoo.com
2,bskai,228342,Male,"Nayarit, Mexico",1990-12-14 00:00:00,2009-08-31 00:00:00,2014-05-12 16:35:00,$2b$12$Xm9lfi62V0McWvSTPvXvtOZ604DEVdJG7OTmowg...,bskai@outlook.com
3,terune_uzumaki,327311,Female,"Malaysia, Kuantan",1998-08-24 00:00:00,2010-05-10 00:00:00,2012-10-18 19:06:00,$2b$12$8sbo6xH9thvzVoPC97JDzuj2wPdGN7f8xg.fLtW...,terune_uzumaki@hotmail.com
4,Bas_G,5015094,Male,"Nijmegen, Nederland",1999-10-24 00:00:00,2015-11-26 00:00:00,2018-05-10 20:53:37,$2b$12$eN2shvFkaKiPlpuWcxv4DOVZWHVdUSQZXpAzDtX...,Bas_G@icloud.com
...,...,...,...,...,...,...,...,...,...
108706,isoann,797785,Male,Poland:,1997-01-13 00:00:00,2011-10-23 00:00:00,2018-02-25 01:20:27,$2b$12$PyESVZdVuWSqr.R6ieoolOX9RuriQgQgu6anI7r...,isoann@aol.com
108707,bumcakee,1396285,Female,"nhollywood, california",1998-07-18 00:00:00,2012-07-14 00:00:00,2017-02-14 00:30:00,$2b$12$/pDgKKnkAFiHr3sM3hPlC.nLj1eQS2x1l4Ksdke...,bumcakee@zoho.com
108708,Scarlet95,2478991,Female,Belgium,1995-10-17 00:00:00,2013-04-24 00:00:00,2016-12-18 08:41:00,$2b$12$Rje5pFgEBt5RRz2EUQoon.eAVdte.X4rHP3BA4n...,Scarlet95@mail.com
108709,Torasori,3975907,Male,"Latvia, Riga",1998-11-18 00:00:00,2014-07-30 00:00:00,2018-05-24 21:34:46,$2b$12$m7Xkul283lL6WFCCcUeisuuGYUt8LBG04WF1XgA...,Torasori@gmx.com
108710,HMicca,1289601,Female,"Birmingham, England",1995-08-12 00:00:00,2012-05-05 00:00:00,2012-11-15 08:10:00,$2b$12$3z9V0m/lhn08g./ogNSGJ.711ovXA.c0OkpGt35...,HMicca@gmail.com

## Cleaning dataset degli anime

In [3]:
df_anime = pd.read_csv("datasets/anime_cleaned.csv")

In [4]:
df_anime.columns

Index(['anime_id', 'title', 'title_english', 'title_japanese',
       'title_synonyms', 'image_url', 'type', 'source', 'episodes', 'status',
       'airing', 'aired_string', 'aired', 'duration', 'rating', 'score',
       'scored_by', 'rank', 'popularity', 'members', 'favorites', 'background',
       'premiered', 'broadcast', 'related', 'producer', 'licensor', 'studio',
       'genre', 'opening_theme', 'ending_theme', 'duration_min',
       'aired_from_year'],
      dtype='object')

In [ ]:
print(df_anime.iloc[0])

anime_id                                                       11013
title                                                  Inu x Boku SS
title_english                              Inu X Boku Secret Service
title_japanese                                                妖狐×僕SS
title_synonyms                                       Youko x Boku SS
image_url          https://myanimelist.cdn-dena.com/images/anime/...
type                                                              TV
source                                                         Manga
episodes                                                          12
status                                               Finished Airing
airing                                                         False
aired_string                            Jan 13, 2012 to Mar 30, 2012
aired                     {'from': '2012-01-13', 'to': '2012-03-30'}
duration                                             24 min. per ep.
rating                                     PG-13 - Teens 13 or older
score                                                           7.63
scored_by                                                     139250
rank                                                          1274.0
popularity                                                       231
members                                                       283882
favorites                                                       2809
background         Inu x Boku SS was licensed by Sentai Filmworks...
premiered                                                Winter 2012
broadcast                                         Fridays at Unknown
related            {'Adaptation': [{'mal_id': 17207, 'type': 'man...
producer           Aniplex, Square Enix, Mainichi Broadcasting Sy...
licensor                                            Sentai Filmworks
studio                                              David Production
genre                         Comedy, Supernatural, Romance, Shounen
opening_theme                                  ['"Nirvana" by MUCC']
ending_theme       ['#1: "Nirvana" by MUCC (eps 1, 11-12)', '#2: ...
duration_min                                                    24.0
aired_from_year                                               2012.0
Name: 0, dtype: object

In [21]:
df_anime

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme,duration_min,aired_from_year
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ...",24.0,2012.0
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi...",24.0,2007.0
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ...",24.0,2008.0
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ...",16.0,2002.0
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)...",24.0,2012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6663,37405,Dokidoki Little Ooyasan,NaN,dokidokiりとる大家さん,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Other,0,Currently Airing,...,NaN,[],NaN,NaN,Collaboration Works,Hentai,[],[],30.0,2018.0
6664,37886,Wo Shi Jiang Xiaobai (2018),I&#039;m Joybo OVA,我是江小白 小剧场,Wo Shi Jiang Xiao Bai: Xiao Ju Chang,https://myanimelist.cdn-dena.com/images/anime/...,ONA,Original,1,Finished Airing,...,NaN,"{'Prequel': [{'mal_id': 36775, 'type': 'anime'...",NaN,NaN,2:10 Animation,"Slice of Life, Drama, Romance",[],[],0.0,2018.0
6665,37255,Genki Genki Non-tan: Obake Mura Meiro,NaN,げんきげんきノンタン おばけむらめいろ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Original,1,Finished Airing,...,NaN,"{'Prequel': [{'mal_id': 25619, 'type': 'anime'...",NaN,NaN,Polygon Pictures,"Music, Kids",[],[],35.0,2015.0
6666,35229,Mr. Men Little Miss,Mr. Men Little Miss,Mr. Men Little Miss / ミスターメン リトルミス,NaN,https://myanimelist.cdn-dena.com/images/anime/...,ONA,Picture book,0,Currently Airing,...,NaN,[],NaN,NaN,Sanrio,Kids,[],[],2.0,2013.0
6667,36315,Mushi Mushi Mura no Nakama-tachi: Minna Ii Tok...,NaN,むしむし村の仲間たち みんないいとこあるんだよ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Original,1,Finished Airing,...,NaN,"{'Alternative version': [{'mal_id': 28549, 'ty...",NaN,NaN,Toei Animation,Kids,[],[],13.0,2017.0

In [5]:
df_anime.drop(columns=["title_japanese", "title_synonyms","airing", "popularity", "members", "background", "premiered", "broadcast", "opening_theme", "ending_theme", "related"], inplace=True)

In [6]:
df_anime['genre'] = df_anime['genre'].apply(lambda x: [g.strip() for g in x.split(",")] if isinstance(x, str) else [])

In [7]:
print(df_anime.iloc[0])

anime_id                                                       11013
title                                                  Inu x Boku SS
title_english                              Inu X Boku Secret Service
image_url          https://myanimelist.cdn-dena.com/images/anime/...
type                                                              TV
source                                                         Manga
episodes                                                          12
status                                               Finished Airing
aired_string                            Jan 13, 2012 to Mar 30, 2012
aired                     {'from': '2012-01-13', 'to': '2012-03-30'}
duration                                             24 min. per ep.
rating                                     PG-13 - Teens 13 or older
score                                                           7.63
scored_by                                                     139250
rank                                                          1274.0
favorites                                                       2809
producer           Aniplex, Square Enix, Mainichi Broadcasting Sy...
licensor                                            Sentai Filmworks
studio                                              David Production
genre                       [Comedy, Supernatural, Romance, Shounen]
duration_min                                                    24.0
aired_from_year                                               2012.0
Name: 0, dtype: object

## Cleaning dataset animelist

In [ ]:
df_animelist = pd.read_csv("datasets/animelists_cleaned.csv")

In [26]:
df_animelist

,username,anime_id,my_watched_episodes,my_start_date,my_finish_date,my_score,my_status,my_rewatching,my_rewatching_ep,my_last_updated,my_tags
0,karthiga,21,586,0000-00-00,0000-00-00,9,1,NaN,0,2013-03-03 10:52:53,NaN
1,karthiga,59,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-10 13:54:51,NaN
2,karthiga,74,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-04-27 16:43:35,NaN
3,karthiga,120,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-03 10:53:57,NaN
4,karthiga,178,26,0000-00-00,0000-00-00,7,2,0.0,0,2013-03-27 15:59:13,NaN
...,...,...,...,...,...,...,...,...,...,...,...
31284025,Yokonightcore,15611,48,2014-00-00,0000-00-00,9,1,NaN,0,2015-09-07 17:33:03,NaN
31284026,Yokonightcore,27815,22,0000-00-00,0000-00-00,9,1,NaN,0,2015-09-07 17:32:05,NaN
31284027,wargod,5945,39,0000-00-00,0000-00-00,8,2,0.0,0,2010-03-29 04:24:12,NaN
31284028,JMc_SetoKai_LoVe,1316,52,0000-00-00,0000-00-00,9,2,NaN,0,2009-12-23 05:45:14,NaN
31284029,hinogurl_mikha,1744,58,0000-00-00,0000-00-00,10,1,0.0,0,2008-04-05 11:36:20,NaN

In [27]:
df_animelist.drop(columns=["my_start_date", "my_finish_date", "my_status", "my_rewatching", "my_rewatching_ep", "my_last_updated", "my_tags"], inplace=True)

In [28]:
df_animelist.head()

   username  anime_id  my_watched_episodes  my_score
0  karthiga        21                  586         9
1  karthiga        59                   26         7
2  karthiga        74                   26         7
3  karthiga       120                   26         7
4  karthiga       178                   26         7

### Cambio degli id nelle liste

In [29]:
df_anime['anime_id'] = pd.to_numeric(df_anime['anime_id'], errors='coerce')
df_anime['episodes'] = pd.to_numeric(df_anime['episodes'], errors='coerce')

# Merge e salvataggio diretto su df_animelist
df_animelist = df_animelist.merge(
    df_anime[['anime_id', 'episodes']],
    on='anime_id',
    how='left'
)

df_animelist['terminato'] = df_animelist['my_watched_episodes'] >= df_animelist['episodes']

df_animelist['stato'] = df_animelist['terminato'].apply(lambda x: 'completed' if x else 'watching')

df_animelist.drop(columns=["episodes"], inplace=True)

In [30]:
df_animelist

,username,anime_id,my_watched_episodes,my_score,terminato,stato
0,karthiga,21,586,9,True,completed
1,karthiga,59,26,7,True,completed
2,karthiga,74,26,7,True,completed
3,karthiga,120,26,7,True,completed
4,karthiga,178,26,7,True,completed
...,...,...,...,...,...,...
31284025,Yokonightcore,15611,48,9,False,watching
31284026,Yokonightcore,27815,22,9,False,watching
31284027,wargod,5945,39,8,True,completed
31284028,JMc_SetoKai_LoVe,1316,52,9,True,completed
31284029,hinogurl_mikha,1744,58,10,False,watching

In [31]:
from bson import ObjectId
# Generazione nuovi _id
df_utenti['_id'] = [ObjectId() for _ in range(len(df_utenti))]
df_anime['_id'] = [ObjectId() for _ in range(len(df_anime))]

# Mappa username → _id utenti
user_map = df_utenti.set_index('username')['_id'].to_dict()

# Mappa anime_id originale → _id degli anime
anime_map = df_anime.set_index('anime_id')['_id'].to_dict()

# Aggiorna df_animelist con i nuovi id
df_animelist['user_id'] = df_animelist['username'].map(user_map)
df_animelist['anime_id'] = df_animelist['anime_id'].map(anime_map)

In [32]:
df_utenti.drop(columns=['user_id'], inplace=True)
df_anime.drop(columns=['anime_id'], inplace=True)

In [33]:
df_animelist

,username,anime_id,my_watched_episodes,my_score,terminato,stato,user_id
0,karthiga,6862332603350ba1fb3e7f51,586,9,True,completed,6862332503350ba1fb3cd688
1,karthiga,6862332603350ba1fb3e7f3e,26,7,True,completed,6862332503350ba1fb3cd688
2,karthiga,6862332603350ba1fb3e7f44,26,7,True,completed,6862332503350ba1fb3cd688
3,karthiga,6862332603350ba1fb3e7f4f,26,7,True,completed,6862332503350ba1fb3cd688
4,karthiga,6862332603350ba1fb3e7f35,26,7,True,completed,6862332503350ba1fb3cd688
...,...,...,...,...,...,...,...
31284025,Yokonightcore,6862332603350ba1fb3e8065,48,9,False,watching,6862332603350ba1fb3e3575
31284026,Yokonightcore,6862332603350ba1fb3e882a,22,9,False,watching,6862332603350ba1fb3e3575
31284027,wargod,6862332603350ba1fb3e8e7a,39,8,True,completed,6862332603350ba1fb3e10d6
31284028,JMc_SetoKai_LoVe,6862332603350ba1fb3e96ae,52,9,True,completed,6862332603350ba1fb3ddd0e
31284029,hinogurl_mikha,6862332603350ba1fb3e8049,58,10,False,watching,6862332603350ba1fb3d5973

In [34]:
print(df_anime.dtypes)
print(df_utenti.dtypes)
print(df_animelist.dtypes)

title               object
title_english       object
image_url           object
type                object
source              object
episodes             int64
status              object
aired_string        object
aired               object
duration            object
rating              object
score              float64
scored_by            int64
rank               float64
favorites            int64
producer            object
licensor            object
studio              object
genre               object
duration_min       float64
aired_from_year    float64
_id                 object
dtype: object
username       object
gender         object
location       object
birth_date     object
join_date      object
last_online    object
password       object
email          object
_id            object
dtype: object
username               object
anime_id               object
my_watched_episodes     int64
my_score                int64
terminato                bool
stato                  object
user_id                object
dtype: object

In [35]:
df_anime

,title,title_english,image_url,type,source,episodes,status,aired_string,aired,duration,...,scored_by,rank,favorites,producer,licensor,studio,genre,duration_min,aired_from_year,_id
0,Inu x Boku SS,Inu X Boku Secret Service,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,"Jan 13, 2012 to Mar 30, 2012","{'from': '2012-01-13', 'to': '2012-03-30'}",24 min. per ep.,...,139250,1274.0,2809,"Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"[Comedy, Supernatural, Romance, Shounen]",24.0,2012.0,6862332603350ba1fb3e7f2f
1,Seto no Hanayome,My Bride is a Mermaid,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,"Apr 2, 2007 to Oct 1, 2007","{'from': '2007-04-02', 'to': '2007-10-01'}",24 min. per ep.,...,91206,727.0,2579,"TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"[Comedy, Parody, Romance, School, Shounen]",24.0,2007.0,6862332603350ba1fb3e7f30
2,Shugo Chara!! Doki,Shugo Chara!! Doki,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,"Oct 4, 2008 to Sep 25, 2009","{'from': '2008-10-04', 'to': '2009-09-25'}",24 min. per ep.,...,37129,1508.0,802,"TV Tokyo, Sotsu",NaN,Satelight,"[Comedy, Magic, School, Shoujo]",24.0,2008.0,6862332603350ba1fb3e7f31
3,Princess Tutu,Princess Tutu,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,"Aug 16, 2002 to May 23, 2003","{'from': '2002-08-16', 'to': '2003-05-23'}",16 min. per ep.,...,36501,307.0,3344,"Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"[Comedy, Drama, Magic, Romance, Fantasy]",16.0,2002.0,6862332603350ba1fb3e7f32
4,Bakuman. 3rd Season,Bakuman.,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,"Oct 6, 2012 to Mar 30, 2013","{'from': '2012-10-06', 'to': '2013-03-30'}",24 min. per ep.,...,107767,50.0,2082,"NHK, Shueisha",NaN,J.C.Staff,"[Comedy, Drama, Romance, Shounen]",24.0,2012.0,6862332603350ba1fb3e7f33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6663,Dokidoki Little Ooyasan,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Other,0,Currently Airing,"May 25, 2018 to ?","{'from': '2018-05-25', 'to': None}",30 min.,...,33,NaN,21,NaN,NaN,Collaboration Works,[Hentai],30.0,2018.0,6862332603350ba1fb3e9936
6664,Wo Shi Jiang Xiaobai (2018),I&#039;m Joybo OVA,https://myanimelist.cdn-dena.com/images/anime/...,ONA,Original,1,Finished Airing,"May 25, 2018","{'from': '2018-05-25', 'to': '2018-05-25'}",Unknown,...,0,12719.0,1,NaN,NaN,2:10 Animation,"[Slice of Life, Drama, Romance]",0.0,2018.0,6862332603350ba1fb3e9937
6665,Genki Genki Non-tan: Obake Mura Meiro,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Original,1,Finished Airing,"Jun 3, 2015","{'from': '2015-06-03', 'to': '2015-06-03'}",35 min.,...,5,10253.0,0,NaN,NaN,Polygon Pictures,"[Music, Kids]",35.0,2015.0,6862332603350ba1fb3e9938
6666,Mr. Men Little Miss,Mr. Men Little Miss,https://myanimelist.cdn-dena.com/images/anime/...,ONA,Picture book,0,Currently Airing,"Nov 29, 2013 to ?","{'from': '2013-11-29', 'to': None}",2 min.,...,7,11396.0,1,NaN,NaN,Sanrio,[Kids],2.0,2013.0,6862332603350ba1fb3e9939
6667,Mushi Mushi Mura no Nakama-tachi: Minna Ii Tok...,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Original,1,Finished Airing,2017,"{'from': None, 'to': None}",13 min.,...,4,11396.0,0,NaN,NaN,Toei Animation,[Kids],13.0,2017.0,6862332603350ba1fb3e993a

In [36]:
df_anime.to_csv("datasets/anime.csv", index=False)
df_utenti.to_csv("datasets/users.csv", index=False)
df_animelist.to_csv("datasets/animelists.csv", index=False)

In [37]:
df_anime.to_json("datasets/anime.json", orient='records', lines=True)
df_utenti.to_json("datasets/users.json", orient='records', lines=True)
df_animelist.to_json("datasets/animelists.json", orient='records', lines=True)

OverflowError: Unsupported UTF-8 sequence length when encoding string

## Caricamento su MongoDB

In [38]:
from pymongo import MongoClient

def sposta_id_primo(df):
    cols = list(df.columns)
    cols.remove('_id')
    return df[['_id'] + cols]


df_utenti = sposta_id_primo(df_utenti)
df_anime = sposta_id_primo(df_anime)

# Connessione al database
client = MongoClient("mongodb://localhost:27017/")
db_name = "anime_db"

# Droppa il database
client.drop_database(db_name)
db = client[db_name]
print(f"Database '{db_name}' eliminato e ricreato.")

# Inserimento dati dai DataFrame
users_records = df_utenti.to_dict(orient='records')
anime_records = df_anime.to_dict(orient='records')
animelist_records = df_animelist.to_dict(orient='records')

db.users.insert_many(users_records)
print(f"Inseriti {len(users_records)} utenti.")

db.anime.insert_many(anime_records)
print(f"Inseriti {len(anime_records)} anime.")

db.user_anime_list.insert_many(animelist_records)
print(f"Inseriti {len(animelist_records)} record in animelists.")

Database 'anime_db' eliminato e ricreato.
Inseriti 108711 utenti.
Inseriti 6668 anime.
Inseriti 31284030 record in animelists.